version: '3'

services: 
  mysql-dev:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mgse_user
      MYSQL_PASSWORD: ageofempires3
      MYSQL_DATABASE: mgse_user_db
    ports: 
      - "3308:3306"
    volumes:
      - "./my.cnf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
  
  client:
    image: mariadb
    depends_on:
      - mysql-dev
    command: mysql -umgse_user -pageofempires3 -hmysql-dev mgse_user_db

  admin:
    image: adminer
    ports: 
      - 8080:8080