version: '3'

services:
  mysql-dev:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mgse_user
      MYSQL_PASSWORD: ageofempires3
      MYSQL_DATABASE: mgse_user_db
    ports:
      - "3308:3306"
    volumes:
      - "./my.cnf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"

  client:
    image: mysql:5
    depends_on:
      - mysql-dev
    command: mysql -umgse_user -pageofempires3 -hmysql-dev mgse_user_db

  admin:
    image: adminer
    ports:
      - 8081:8080

  restapi:
    container_name: restapi
    restart: always
    build:
      context: ../application/restapi
      dockerfile: Dockerfile
    depends_on:
      - mysql-dev
    ports:
      - 8082:8080

  frontend:
    container_name: frontend
    build:
      context: ../application/frontend
      dockerfile: Dockerfile
    depends_on:
      - restapi
    volumes:
      - '/usr/src/app/node_modules'
    ports:
      - '8083:4200'
